backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)
local_backend: true

publish_mode: editorial_workflow # Allows you to save drafts before publishing them

locale: 'fr'

slug:
    encoding: 'ascii'
    clean_accents: true

media_folder: static/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /images/uploads

collections:
    - name: 'project' # Used in routes, e.g., /admin/collections/project
        label: 'project' # Used in the UI
        folder: 'content/projects' # The path to the folder where our blog posts are stored
        create: true # Allow users to create new documents in this collection
        fields: # The fields for each document
            - { label: 'Id', name: 'id', widget: 'string' }
            - { label: 'Src', name: 'src', widget: 'string' }
            - { label: 'Alt', name: 'alt', widget: 'string' }
            - { label: 'Title', name: 'title', widget: 'string' }
            - { label: 'Content', name: 'content', widget: 'markdown' }
