backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)
local_backend: true

publish_mode: editorial_workflow # Allows you to save drafts before publishing them

locale: "fr"

slug:
    encoding: "ascii"
    clean_accents: true

media_folder: static/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /images/uploads

collections:
    - name: "project" # Used in routes, e.g., /admin/collections/project
      label: "project" # Used in the UI
      folder: "content/projects" # The path to the folder where our blog posts are stored
      slug: "{{slug}}"
      create: true # Allow users to create new documents in this collection
      fields: # The fields for each document
          - { label: "Id", name: "id", widget: "string" }
          - { label: "Image", name: "src", widget: "image" }
          - { label: "Alt", name: "alt", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Résumé", name: "recap", widget: "string" }
          - { label: "Corps de l'article", name: "body", widget: "markdown" }
    - name: "watch"
      label: "watch"
      folder: "content/watchs"
      slug: "{{slug}}"
      create: true
      fields:
          - { label: "Id", name: "id", widget: "string" }
          - { label: "Href", name: "href", widget: "file" }
          - { label: "Image", name: "src", widget: "image" }
          - { label: "Alt", name: "alt", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Résumé", name: "recap", widget: "string" }
          - { label: "Corps de l'article", name: "body", widget: "markdown" }
    - name: "skill"
      label: "skill"
      folder: "content/skills"
      slug: "{{slug}}"
      create: true
      fields:
          - { label: "Image", name: "src", widget: "image" }
          - { label: "Alt", name: "alt", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - {
                label: "Niveau",
                name: "level",
                widget: "number",
                value_type: "int",
                min: 1,
                max: 4,
                step: 1,
            }
